backend:
  name: github
  repo: tjeuba0/linhchiauraBlog
  branch: main
  base_url: https://sveltia-cms-auth.khoivandev.workers.dev

media_folder: "/public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Đọc sâu"
    folder: "src/content/blog"
    media_folder: "/public/images"
    public_folder: "/images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - label: "Chủ đề"
        name: "tag"
        widget: "select"
        options:
          - "Chữa lành - Con người & Các mối quan hệ"
          - "Phát triển bản thân"
          - "Não bộ & Tâm lý"
          - "Khoa học & Các hệ tư tưởng"
      - { label: "Ngày đăng", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Phút đọc", name: "readingMinutes", widget: "number", default: 3 }
      - { label: "Trích đoạn", name: "excerpt", widget: "text" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
